name: Hex Semantic Project Ingest
on:
  pull_request:
    paths:
      - 'semantic_models/**/*.yml'
  push:
    branches:
      - main
      - master
    paths:
      - 'semantic_models/**/*.yml'
env:
  TOKEN: ${{ secrets.HEX_SEMANTIC_INGEST_TOKEN }}
  DIRECTORY: semantic_models
jobs:
  hex-semantic-project-ingest:
    runs-on: ubuntu-latest
    steps:
    - name: Verify token
      run: |
        if [ -z "$TOKEN" ]; then
          echo "❌ Error: TOKEN not found. Please make sure the secret referenced in your workflow file exists in your repository."
          exit 1
        else
          echo "Token exists, proceeding..."
        fi
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Zip up files
      run: |
          cd $DIRECTORY
          zip -r repo.zip .
    - name: Ingest Semantic Project
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
          response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
            -F "data=@$DIRECTORY/repo.zip" \
            https://app.hex.tech/api/v1/semantic-projects/019eac82-fd17-77d7-b194-14c48b8fcc19/ingest \
            -H "Authorization: Bearer $TOKEN")
          if [ "$response" -eq 201 ]; then
            echo "✅ Successfully ingested semantic project"
            cat response.txt | jq -r '[ .contents[] // "No content", , .problems[].display? // "No problems detected", , "Hex trace ID: " + .traceId ]|join("\n")'
          else
            echo "❌ Failed to ingest semantic project"
            cat response.txt | jq &> /dev/null && cat response.txt | jq -r '[ .reason, , .problems[].display? // "Unknown error", , "Hex trace ID: " + .traceId ]|join("\n")' || cat response.txt
            exit 1
          fi
    - name: Ingest Semantic Project (dry run)
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      run: |
          response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
            -F "data=@$DIRECTORY/repo.zip" \
            -F "dryRun=true" \
            https://app.hex.tech/api/v1/semantic-projects/019eac82-fd17-77d7-b194-14c48b8fcc19/ingest \
            -H "Authorization: Bearer $TOKEN")
          if [ "$response" -eq 201 ]; then
            echo "✅ Successfully ingested semantic project"
            cat response.txt | jq -r '[ .contents[] // "No content", , .problems[].display? // "No problems detected", , "Hex trace ID: " + .traceId ]|join("\n")'
          else
            echo "❌ Failed to ingest semantic project"
            cat response.txt | jq &> /dev/null && cat response.txt | jq -r '[ .reason, , .problems[].display? // "Unknown error", , "Hex trace ID: " + .traceId ]|join("\n")' || cat response.txt
            exit 1
          fi
